version: '3'
services:

  app:
    image: webdevops/php-nginx-dev:7.4-alpine
    container_name: app
    restart: always
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/src/public
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=-1
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_PORT=9000
      - XDEBUG_MAX_NESTING_LEVEL=1000
      - XDEBUG_DISCOVER_CLIENT_HOST=1
    ports:
      - '80:80'
    volumes:
      - './app:/app:rw,cached'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
      - 'PMA_HOST=mysqldb'
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    image: 'mysql:latest'
    container_name: mysqldb
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=dev'
      - 'MYSQL_PASSWORD=dev'
    ports:
      - '8989:3306'
    volumes:
      - './data/db/mysql:/var/lib/mysql'
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elk01
    restart: always
    environment:
      - node.name=elk01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elk-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  elastichq:
    image: elastichq/elasticsearch-hq
    container_name: elastichq
    restart: always
    environment:
      - HQ_DEFAULT_URL=http://elk01:9200
      - HQ_DEBUG=True
      - HQ_ENABLE_SSL=False
      - HQ_VERIFY_CERTS=False
    ports:
      - 5000:5000
    networks:
      - elastic
  
volumes:
  elk-data:
    driver: local

networks:
  elastic:
    driver: bridge
